comment:
  layout: "condensed_header, diff, files, condensed_footer"
  behavior: default
  require_base: true
  require_head: true
  require_changes: true
  hide_project_coverage: false

github_checks:
  annotations: true

coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto
